--@Autor:  Argueta Bravo y Castilla Padilla
--@Fecha creación: dd/mm/yyyy
--@Descripción: Creación de fragmentos en el sitio 1 (nodo 2)
clear screen
whenever sqlerror exit rollback;
drop table if exists USUARIO_F5_PCP_S2;
drop table if exists TIPO_SERIE_R_PCP_S2;
drop table if exists TIPO_CUENTA_R_PCP_S2;
drop table if exists STATUS_PROGRAMA;
drop table if exists PAIS_R_PCP_S2;

CREATE TABLE PAIS_R_PCP_S2(
    PAIS_ID       NUMBER(2, 0)    NOT NULL,
    CLAVE         VARCHAR2(4)     NOT NULL,
    NOMBRE        VARCHAR2(50)    NOT NULL,
    CONTINENTE    VARCHAR2(3)     NOT NULL,
    CONSTRAINT PAIS_R_PCP_S2_PK PRIMARY KEY (PAIS_ID)
)
;

CREATE TABLE STATUS_PROGRAMA(
    STATUS_PROGRAMA_ID    NUMBER(2, 0)     NOT NULL,
    CLAVE                 VARCHAR2(40)     NOT NULL,
    DESCRIPCION           VARCHAR2(500)    NOT NULL,
    CONSTRAINT STATUS_PROGRAMA_PK PRIMARY KEY (STATUS_PROGRAMA_ID)
)
;

CREATE TABLE TIPO_CUENTA_R_PCP_S2(
    TIPO_CUENTA_ID    NUMBER(2, 0)     NOT NULL,
    CLAVE             VARCHAR2(40)     NOT NULL,
    DESCRIPCION       VARCHAR2(500)    NOT NULL,
    COSTO_MENSUAL     NUMBER(10, 2)    NOT NULL,
    CONSTRAINT TIPO_CUENTA_R_PCP_S2_PK PRIMARY KEY (TIPO_CUENTA_ID)
)
;

CREATE TABLE TIPO_SERIE_R_PCP_S2(
    TIPO_SERIE_ID    NUMBER(2, 0)     NOT NULL,
    CLAVE            VARCHAR2(40)     NOT NULL,
    DESCRIPCION      VARCHAR2(500)    NOT NULL,
    CONSTRAINT TIPO_SERIE_R_PCP_S2_PK PRIMARY KEY (TIPO_SERIE_ID)
)
;

CREATE TABLE USUARIO_F5_PCP_S2(
    USUARIO_ID          NUMBER(10, 0)    NOT NULL,
    EMAIL               VARCHAR2(200)    NOT NULL,
    NOMBRE              VARCHAR2(40)     NOT NULL,
    AP_PATERNO          VARCHAR2(40)     NOT NULL,
    AP_MATERNO          VARCHAR2(40)     NOT NULL,
    FECHA_INGRESO       DATE             NOT NULL,
    FECHA_CUENTA_FIN    DATE             NOT NULL,
    VIGENTE             NUMBER(1, 0)     NOT NULL,
    TIPO_CUENTA_ID      NUMBER(2, 0)     NOT NULL,
    CONSTRAINT USUARIO_F5_PCP_S2_PK PRIMARY KEY (USUARIO_ID), 
    CONSTRAINT USUARIO_F5_PCP_S2_TIPO_CUENTA_ID_FK FOREIGN KEY (TIPO_CUENTA_ID)
    REFERENCES TIPO_CUENTA_R_PCP_S2(TIPO_CUENTA_ID)
)
;